// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAffix: typeof import("element-plus/es")["ElAffix"]
  const ElAside: typeof import("element-plus/es")["ElAside"]
  const ElCarousel: typeof import("element-plus/es")["ElCarousel"]
  const ElCarouselItem: typeof import("element-plus/es")["ElCarouselItem"]
  const ElContainer: typeof import("element-plus/es")["ElContainer"]
  const ElFooter: typeof import("element-plus/es")["ElFooter"]
  const ElHeader: typeof import("element-plus/es")["ElHeader"]
  const ElImage: typeof import("element-plus/es")["ElImage"]
  const ElMain: typeof import("element-plus/es")["ElMain"]
  const ElScrollbar: typeof import("element-plus/es")["ElScrollbar"]
  const ElTabPane: typeof import("element-plus/es")["ElTabPane"]
  const ElTabs: typeof import("element-plus/es")["ElTabs"]
}
export {}
